### ISSUE TITLE
/happenstance is slow

### ISSUE THREAD

**Issue by ivankozik** [bellroy/predictionbook-legacy#7]
http://predictionbook.com/happenstance takes quite a while to load (about 26 seconds).  I don't know what's wrong here; perhaps missing indexes?

```
time lynx -source 'http://predictionbook.com/happenstance' > /dev/null
lynx -source 'http://predictionbook.com/happenstance' > /dev/null  0.02s user 0.03s system 0% cpu 26.433 total
```

**Comment by matthewfallshaw** [comment]
Fixed by 8f0c2043b7c1e70a2c3c39ccb9f8f7fde75488a1
